[project]
name = "projektpraktikum-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "manim>=0.18.1",
    "numpy>=1.26.4",
]

