[project]
name = "projektpraktikum-i"
version = "0.1.0"
description = "Praxisübung NLA - Projektpraktikum I - WiSe24/25"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "manim>=0.18.1",
    "numpy>=1.26.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
]
