[project]
name = "projektpraktikum-i"
version = "0.1.0"
description = "Praxisübung NLA - Projektpraktikum I - WiSe24/25"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "manim>=0.18.1",
    "numpy>=1.26.4",
]

